#!/bin/bash

#set -e
#set -x

source /etc/opt/copilot
readonly PROG_DIR=$(readlink -m $(dirname $0))

temporary_fixes () {
    echo dnsmasq-base hold |dpkg --set-selections
}

# ==== OS ====

update_os() {
    apt-get -y update
    apt-get -y upgrade
}

# ==== CO-PILOT BASE ====

install_co-pilot_deps() {
     # usbmount auto-mounts usb sticks
     apt-get -y install usbmount
}

setup_copilot_env() {
    if grep -Fxq "COPILOT_PROFILE_CONFIG_DIRECTORY" /etc/environment
    then
        echo "Copilot environment already configured. Skipping..."
    else
        # Create global environment variable for copilot to use
        echo "COPILOT_PROFILE_CONFIG_DIRECTORY=${COPILOT_PROFILE_CONFIG_DIRECTORY}" >> /etc/environment
        echo "COPILOT_TEMPORARY_CONFIG_DIRECTORY=${COPILOT_TEMPORARY_CONFIG_DIRECTORY}" >> /etc/environment
        echo "COPILOT_DEFAULT_CONFIG_DIRECTORY=${COPILOT_DEFAULT_CONFIG_DIRECTORY}" >> /etc/environment
    fi
}

# ==== FLASK ====

install_flask_deps() {
    #Install Flask dependencies
    apt-get -y install python-dev
    apt-get -y install curl
    apt-get -y install python2.7-dev
    apt-get -y install python-pysqlite2
    # Add pip to path
    export PATH="/usr/local/bin:$PATH"

    # Bcrypt Dependencies
    apt-get -y install build-essential
    #apt-get -y install libffi-dev
}

install_flask() {
    #install flask & WTForms
    pip install flask
    pip install flask-wtf
    pip install SQLAlchemy
    pip install Flask-SQLAlchemy
    pip install flask-bcrypt
    pip install Flask-Login
}

setup_flask_env() {
    # # Get rid of the application root in the bp_config
    # sed -i '/^APPLICATION_ROOT.*/d' $COPILOT_DIR/instance/bp_config.py

    # Add a random CSRF session key.
    local CSRF=$(openssl rand -base64 32)
    sed -i "s/^\(CSRF_SESSION_KEY\s=\s\).*$/\1\"${CSRF}\"/" $COPILOT_DIR/instance/config.py
    sed -i "s/^\(CSRF_SESSION_KEY\s=\s\).*$/\1\"${CSRF}\"/" $COPILOT_DIR/instance/bp_config.py

    # Add a random secret key for signing cookies
    local SECRET=$(openssl rand -base64 32)
    sed -i "s/^\(SECRET_KEY\s=\s\).*$/\1\"${SECRET}\"/" $COPILOT_DIR/instance/config.py
    sed -i "s/^\(SECRET_KEY\s=\s\).*$/\1\"${SECRET}\"/" $COPILOT_DIR/instance/bp_config.py
}

# ==== WSGI ====
install_wsgi() {
    apt-get -y install  nginx supervisor
    pip install gunicorn
    apt-get -y install python-pip
    pip install watchdog
}

setup_wsgi() {
    setup_nginx
    setup_supervisor
}

setup_nginx() {
    if [[ -a "/etc/nginx/sites-enabled/default" ]]
    then
        rm /etc/nginx/sites-enabled/default
        service nginx start
        cp  $COPILOT_DIR/templates/nginx_sites /etc/nginx/sites-available/copilot
        ln -s /etc/nginx/sites-available/copilot /etc/nginx/sites-enabled/copilot
        #enable
        update-rc.d nginx enable
        service nginx restart
    else
        echo "Nginx already setup. Skipping..."
    fi
}

setup_supervisor() {
    if grep -Fxq "PLUGIN_DIR_REPLACE_STRING" /etc/supervisor/conf.d/supervisord.conf
    then
        # replace the various environment variables with the actual value of the vars
        # Using @ as the sed seperator so that we don't get errors when using double quotes
        cat $COPILOT_DIR/templates/supervisor \
            | sed "s@PLUGIN_DIR_REPLACE_STRING@${COPILOT_PLUGINS_DIRECTORY}@" \
            | sed "s@COPILOT_PROFILE_DIR_REPLACE_STRING@${COPILOT_PROFILE_CONFIG_DIRECTORY}@" \
            | sed "s@COPILOT_TEMP_DIR_REPLACE_STRING@${COPILOT_TEMPORARY_CONFIG_DIRECTORY}@" \
            | sed "s@COPILOT_DEFAULT_DIR_REPLACE_STRING@${COPILOT_DEFAULT_CONFIG_DIRECTORY}@" \
                  > /etc/supervisor/conf.d/supervisord.conf
        #enable
        update-rc.d supervisor enable
    else
        echo "Supervisor already setup. Skipping...."
    fi
}

# ==== AVAHI ====

install_avahi() {
    apt-get -y install avahi-daemon
    update-rc.d avahi-daemon enable
    service avahi-daemon restart
}

# ==== PLUGINS ====

install_plugins() {
    echo "Installing plugins."

    if grep -Fxq "COPILOT_PLUGINS_DIRECTORY" /etc/environment
    then
        echo "Plugins already added to environment. Skipping..."
    else
        # Create global environment variable for copilot to use
        echo "COPILOT_PLUGINS_DIRECTORY=${COPILOT_PLUGINS_DIRECTORY}" >> /etc/environment
    fi

    cd "${COPILOT_PLUGINS_DIRECTORY}"
    cd plugins

    for path in "${COPILOT_PLUGINS_DIRECTORY}"plugins/*; do
        [ -d "${path}" ] || continue # if not a directory, skip
        dirname="$(basename "${path}")"
        echo "Beginning install of plugin $dirname"
        # Run installation script
        if [ -a "${path}"/install ]; then
            "$path"/install
        fi
        # Add supervisor configs to supervisor
        if [ -a "$path"/supervisor.conf ]; then
            # replace COPILOT_PLUGINS_DIRECTORY with the actual value of the var
            # Using @ as the sed seperator so that we don't get errors when using double quotes
            cat "$path"/supervisor.conf \
                | sed "s@COPILOT_PLUGINS_DIRECTORY@${COPILOT_PLUGINS_DIRECTORY}@" \
                >> /etc/supervisor/conf.d/supervisord.conf
        fi
        echo "Plugin $dirname installed"
    done
    echo "All plugins installed"
}

dependencies() {
    # lack of entropy slows installing massively
    apt-get install -y haveged
    install_flask_deps
}

install() {
    #create setup directory
    mkdir -p $SETUP_DIR
    #Create website Directory
    mkdir -p $WEB_DIR
    setup_copilot_env
    setup_flask_env
    install_avahi
    install_flask
    install_wsgi
    install_avahi
}

setup() {
    setup_wsgi
}

main() {
    update_os
    dependencies
    install
    setup
    cd $COPILOT_DIR
    install_plugins
    cd $PROG_DIR
    touch "${INSTALL_FLAG}"
}

main
