#!/bin/bash

start_create_ap() {
    local wlan_name=$(awk "NR==3 {print \$1}" /proc/net/wireless |grep -E "^w.*$" |sed 's/://')

    # If we can't find the wireless name in /proc/net/wireless we should fall back.
    if [[ -z "${wlan_name-}" ]]; then
        wlan_name=$(find /sys/class/net/w* | xargs -I % find %/wireless |cut -d / -f 5)
    fi

    # If we still could not set it, then we should abort.
    if [[ -z "${wlan_name-}" ]]; then
        echo_error "No wireless interface found. Exiting."
        exit 1
    fi

    local default_profile="$wlan_name eth0 copilot copilot_pass"

    if [[ -e /tmp/copilot/ap.conf ]]; then
        echo "Starting with a custom create_ap profile."
        local commands=$(cat /tmp/copilot/ap.conf)
        /usr/bin/create_ap ${commands}
    else
        echo "Starting with the default create_ap profile."
        /usr/bin/create_ap ${default_profile}
    fi
}

kill_all() {
    echo ${1}
    set -x
    create_ap --stop $(create_ap --list| cut -d " " -f 1)
    set +x
    exit 0
}

echo_error(){
    >&2 echo "$@";
}

main() {
    start_create_ap
}
trap 'kill_all' EXIT
main
