#!/usr/bin/env bash

set -e
set -x

readonly PACKAGE_NAME=example

#Install some dependencies, etc
prepare() {
    echo "preparing package $PACKAGE_NAME"
}

#Install the actual package
install() {
    echo "installing package $PACKAGE_NAME"
}

#Configure package
setup() {
    echo "configuring package $PACKAGE_NAME"
}

main() {
    prepare
    install
    setup
}

main
